[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn api_v2:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 8000
timeout = 300